
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "MyFinanceAPI.Api/MyFinanceAPI.Api.csproj"
RUN dotnet publish "MyFinanceAPI.Api/MyFinanceAPI.Api.csproj" -c Release -o /app
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
ENV ASPNETCORE_URLS=http://0.0.0.0:8080
EXPOSE 8080
COPY --from=build /app ./
ENTRYPOINT ["dotnet","MyFinanceAPI.Api.dll"]
