// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFinanceAPI.Data.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyFinanceAPI.Data.Migrations
{
    [DbContext(typeof(ContextDB))]
    [Migration("20261006015603_Integridade")]
    partial class Integridade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DataOperacao")
                        .HasColumnType("text");

                    b.Property<bool>("EhParcelado")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParcelaAtual")
                        .HasColumnType("integer");

                    b.Property<int?>("QuantidadeParcelas")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id")
                        .HasName("PK_Accounts");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.Banco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Agencia")
                        .HasColumnType("text");

                    b.Property<bool?>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("NomeBanco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroConta")
                        .HasColumnType("text");

                    b.Property<decimal>("SaldoInicial")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("TipoCartaoId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("banco_pkey");

                    b.HasIndex("TipoCartaoId");

                    b.HasIndex("UserId", "NomeBanco")
                        .IsUnique()
                        .HasDatabaseName("UX_Banco_UserId_NomeBanco");

                    b.ToTable("Banco", (string)null);
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NaturezaOperacao")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SubCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK_Categories");

                    b.HasIndex("UserId", "Name", "SubCategory")
                        .IsUnique()
                        .HasDatabaseName("UX_Categories_UserId_Name_SubCategory");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.ContaVencimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Dia")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("ContaVencimento_pkey");

                    b.HasIndex("ContaId");

                    b.HasIndex("UserId");

                    b.ToTable("ContaVencimento", (string)null);
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.ExtratoBancario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("BancoId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("DataFimPeriodo")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataImportacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DataInicioPeriodo")
                        .HasColumnType("date");

                    b.Property<Guid>("LoteImportacaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("NomeArquivo")
                        .HasColumnType("text");

                    b.Property<string>("NomeArquivoOrigem")
                        .HasColumnType("text");

                    b.Property<int>("QuantidadeLancamentos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Concluido");

                    b.Property<int?>("TipoCartaoId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorTotal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id")
                        .HasName("ExtratoBancario_pkey");

                    b.HasIndex("BancoId");

                    b.HasIndex("TipoCartaoId");

                    b.HasIndex("UserId");

                    b.ToTable("ExtratoBancario", (string)null);
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.ExtratoBancarioItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int?>("BancoId")
                        .HasColumnType("integer");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("ChaveDescricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ChaveImportacao")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("DataMovimentacao")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<bool?>("EhParcelado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("ExtratoBancarioId")
                        .HasColumnType("integer");

                    b.Property<string>("GrupoParcelamento")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Identificador")
                        .HasColumnType("text");

                    b.Property<string>("NomePessoaTransacao")
                        .HasColumnType("text");

                    b.Property<string>("NumeroFatura")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<int?>("ParcelaAtual")
                        .HasColumnType("integer");

                    b.Property<int?>("PessoaMovimentacaoId")
                        .HasColumnType("integer");

                    b.Property<int?>("QuantidadeParcelas")
                        .HasColumnType("integer");

                    b.Property<int?>("TipoCartaoId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoLancamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TipoMovimentacaoId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id")
                        .HasName("ExtratoBancarioItem_pkey");

                    b.HasIndex("BancoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("DataMovimentacao")
                        .HasDatabaseName("idx_extratobancarioitem_datamov");

                    b.HasIndex("ExtratoBancarioId")
                        .HasDatabaseName("idx_extratobancarioitem_extrato");

                    b.HasIndex("PessoaMovimentacaoId");

                    b.HasIndex("TipoCartaoId");

                    b.HasIndex("TipoMovimentacaoId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ExtratoBancarioItem_UserId");

                    b.HasIndex("UserId", "BancoId", "ChaveImportacao")
                        .IsUnique()
                        .HasDatabaseName("UX_ExtratoBancarioItem_ChaveImportacao")
                        .HasFilter("\"ChaveImportacao\" IS NOT NULL");

                    b.ToTable("ExtratoBancarioItem", (string)null);
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.ItemLista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DataTarefa")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<TimeOnly?>("HorarioTarefa")
                        .HasColumnType("time without time zone");

                    b.Property<int>("ListaId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<int?>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id")
                        .HasName("itemlista_pkey");

                    b.HasIndex("ListaId");

                    b.HasIndex("UserId");

                    b.ToTable("ItemLista", (string)null);
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.Lista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<int>("TipoMovimentacao")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("lista_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("Lista", (string)null);
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.MovimentacaoDiaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int?>("BancoId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DataMovimentacao")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Identificador")
                        .HasColumnType("text");

                    b.Property<string>("NomePessoaTransacao")
                        .HasColumnType("text");

                    b.Property<int?>("TipoCartaoId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoLancamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TipoMovimentacaoId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id")
                        .HasName("movimentacaodiaria_pkey");

                    b.HasIndex("BancoId");

                    b.HasIndex("TipoCartaoId");

                    b.HasIndex("TipoMovimentacaoId");

                    b.HasIndex("UserId");

                    b.ToTable("MovimentacaoDiaria", (string)null);
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.PessoaMovimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("NomePessoa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TipoMovimentacaoId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PessoaMovimentacao_pkey");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("TipoMovimentacaoId");

                    b.HasIndex("UserId", "NomePessoa")
                        .IsUnique()
                        .HasDatabaseName("UX_PessoaMovimentacao_UserId_NomePessoa");

                    b.ToTable("PessoaMovimentacao", (string)null);
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.TipoCartao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("NomeTipoCartao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("tipocartao_pkey");

                    b.HasIndex("UserId", "NomeTipoCartao")
                        .IsUnique()
                        .HasDatabaseName("UX_TipoCartao_UserId_NomeTipoCartao");

                    b.ToTable("TipoCartao", (string)null);
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.TipoMovimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeTipoMovimentacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorMeta")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id")
                        .HasName("tipomovimentacao_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("TipoMovimentacao", null, t =>
                        {
                            t.HasCheckConstraint("tipomovimentacao_valormeta_check", "\"ValorMeta\" >= 0");
                        });
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EhParcelado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("IdAccount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<int?>("ParcelaAtual")
                        .HasColumnType("integer");

                    b.Property<int?>("QuantidadeParcelas")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Value")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id")
                        .HasName("PK_Transactions");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IdAccount");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("StatusAtivo")
                        .HasColumnType("boolean");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("MyFinanceAPI.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("MyFinanceAPI.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFinanceAPI.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("MyFinanceAPI.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.Account", b =>
                {
                    b.HasOne("MyFinanceAPI.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Accounts_Categories_CategoryId");

                    b.HasOne("MyFinanceAPI.Domain.Entities.Usuario", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Accounts_AspNetUsers_UserId");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.Banco", b =>
                {
                    b.HasOne("MyFinanceAPI.Domain.Entities.TipoCartao", "TipoCartao")
                        .WithMany()
                        .HasForeignKey("TipoCartaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_banco_tipocartao");

                    b.HasOne("MyFinanceAPI.Domain.Entities.Usuario", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Banco_AspNetUsers_UerId");

                    b.Navigation("TipoCartao");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.Category", b =>
                {
                    b.HasOne("MyFinanceAPI.Domain.Entities.Usuario", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Categories_AspNetUsers_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.ContaVencimento", b =>
                {
                    b.HasOne("MyFinanceAPI.Domain.Entities.Account", "Account")
                        .WithMany("ContaVencimentos")
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ContaVencimento_ContaId_fkey");

                    b.HasOne("MyFinanceAPI.Domain.Entities.Usuario", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("contavencimento_user_fkey");

                    b.Navigation("Account");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.ExtratoBancario", b =>
                {
                    b.HasOne("MyFinanceAPI.Domain.Entities.Banco", null)
                        .WithMany()
                        .HasForeignKey("BancoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("extratobancario_bancoid_fkey");

                    b.HasOne("MyFinanceAPI.Domain.Entities.TipoCartao", null)
                        .WithMany()
                        .HasForeignKey("TipoCartaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ExtratoBancario_TipoCartao_TipoCartaoId");

                    b.HasOne("MyFinanceAPI.Domain.Entities.Usuario", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("extratobancario_user_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.ExtratoBancarioItem", b =>
                {
                    b.HasOne("MyFinanceAPI.Domain.Entities.Banco", "Banco")
                        .WithMany()
                        .HasForeignKey("BancoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("extratobancarioitem_bancoid_fkey");

                    b.HasOne("MyFinanceAPI.Domain.Entities.Category", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("extratoBancarioItem_bancoId_fkey");

                    b.HasOne("MyFinanceAPI.Domain.Entities.ExtratoBancario", "ExtratoBancario")
                        .WithMany("Itens")
                        .HasForeignKey("ExtratoBancarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("extratobancarioitem_extrato_fkey");

                    b.HasOne("MyFinanceAPI.Domain.Entities.PessoaMovimentacao", "PessoaMovimentacao")
                        .WithMany()
                        .HasForeignKey("PessoaMovimentacaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("extratobancarioitem_pessoamovimentacaoid_fkey");

                    b.HasOne("MyFinanceAPI.Domain.Entities.TipoCartao", "TipoCartao")
                        .WithMany()
                        .HasForeignKey("TipoCartaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("extratobancarioitem_tipocartaoid_fkey");

                    b.HasOne("MyFinanceAPI.Domain.Entities.TipoMovimentacao", "TipoMovimentacao")
                        .WithMany("ExtratoBancarioItem")
                        .HasForeignKey("TipoMovimentacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("extratobancarioitem_tipomovimentacaoid_fkey");

                    b.HasOne("MyFinanceAPI.Domain.Entities.Usuario", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExtratoBancarioItem_AspNetUsers_UserId");

                    b.Navigation("Banco");

                    b.Navigation("Categoria");

                    b.Navigation("ExtratoBancario");

                    b.Navigation("PessoaMovimentacao");

                    b.Navigation("TipoCartao");

                    b.Navigation("TipoMovimentacao");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.ItemLista", b =>
                {
                    b.HasOne("MyFinanceAPI.Domain.Entities.Lista", "Lista")
                        .WithMany()
                        .HasForeignKey("ListaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("itemlista_listaid_fkey");

                    b.HasOne("MyFinanceAPI.Domain.Entities.Usuario", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ItemLista_AspNetUsers_UserId");

                    b.Navigation("Lista");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.Lista", b =>
                {
                    b.HasOne("MyFinanceAPI.Domain.Entities.Usuario", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Lista_AspNetUsers_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.MovimentacaoDiaria", b =>
                {
                    b.HasOne("MyFinanceAPI.Domain.Entities.Banco", "Banco")
                        .WithMany()
                        .HasForeignKey("BancoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("movimentacaodiaria_bancoid_fkey");

                    b.HasOne("MyFinanceAPI.Domain.Entities.TipoCartao", "TipoCartao")
                        .WithMany()
                        .HasForeignKey("TipoCartaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("movimentacaodiaria_tipocartaoid_fkey");

                    b.HasOne("MyFinanceAPI.Domain.Entities.TipoMovimentacao", "TipoMovimentacao")
                        .WithMany()
                        .HasForeignKey("TipoMovimentacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("movimentacaodiaria_tipomovimentacaoid_fkey");

                    b.HasOne("MyFinanceAPI.Domain.Entities.Usuario", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MovimentacaoDiaria_AspNetUsers_UserId");

                    b.Navigation("Banco");

                    b.Navigation("TipoCartao");

                    b.Navigation("TipoMovimentacao");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.PessoaMovimentacao", b =>
                {
                    b.HasOne("MyFinanceAPI.Domain.Entities.Category", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PessoaMovimentacao_Categories_CategoriaId");

                    b.HasOne("MyFinanceAPI.Domain.Entities.TipoMovimentacao", "TipoMovimentacao")
                        .WithMany()
                        .HasForeignKey("TipoMovimentacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PessoaMovimentacao_TipoMovimentacao_TipoMovimentacaoId");

                    b.HasOne("MyFinanceAPI.Domain.Entities.Usuario", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PessoaMovimentacao_AspNetUsers_UserId");

                    b.Navigation("Categoria");

                    b.Navigation("TipoMovimentacao");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.TipoCartao", b =>
                {
                    b.HasOne("MyFinanceAPI.Domain.Entities.Usuario", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tipocartao_aspnetusers");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.TipoMovimentacao", b =>
                {
                    b.HasOne("MyFinanceAPI.Domain.Entities.Usuario", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tipomovimentacao_aspnetusers");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("MyFinanceAPI.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Transactions_Categories_CategoryId");

                    b.HasOne("MyFinanceAPI.Domain.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("IdAccount")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Transactions_Accounts_IdAccount");

                    b.HasOne("MyFinanceAPI.Domain.Entities.Usuario", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Transactions_AspNetUsers_UserId");

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.Account", b =>
                {
                    b.Navigation("ContaVencimentos");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.ExtratoBancario", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("MyFinanceAPI.Domain.Entities.TipoMovimentacao", b =>
                {
                    b.Navigation("ExtratoBancarioItem");
                });
#pragma warning restore 612, 618
        }
    }
}
