CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "AspNetRoles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NomeUsuario" text NOT NULL,
    "StatusAtivo" boolean NOT NULL,
    "Role" text NOT NULL,
    "CriadoEm" timestamp with time zone NOT NULL,
    "AtualizadoEm" timestamp with time zone NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" integer NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" integer NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "SubCategory" text NOT NULL,
    "NaturezaOperacao" integer,
    "Status" integer NOT NULL,
    "DataAlteracao" timestamp without time zone NOT NULL DEFAULT (now()),
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Categories_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Lista" (
    "Id" serial NOT NULL,
    "Nome" text NOT NULL,
    "TipoMovimentacao" integer,
    "Status" boolean,
    "DataAlteracao" timestamp without time zone NOT NULL DEFAULT (now()),
    "UserId" integer NOT NULL,
    CONSTRAINT lista_pkey PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Lista_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "TipoCartao" (
    "Id" serial NOT NULL,
    "NomeTipoCartao" text NOT NULL,
    "Descricao" text,
    "UserId" integer,
    CONSTRAINT tipocartao_pkey PRIMARY KEY ("Id"),
    CONSTRAINT fk_tipocartao_aspnetusers FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id")
);

CREATE TABLE "TipoMovimentacao" (
    "Id" serial NOT NULL,
    "NomeTipoMovimentacao" text NOT NULL,
    "Descricao" text,
    "ValorMeta" numeric(10,2) DEFAULT 0.0,
    "DataAlteracao" timestamp without time zone NOT NULL DEFAULT (now()),
    "UserId" integer,
    CONSTRAINT tipomovimentacao_pkey PRIMARY KEY ("Id"),
    CONSTRAINT tipomovimentacao_valormeta_check CHECK ("ValorMeta" >= 0),
    CONSTRAINT fk_tipomovimentacao_aspnetusers FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id")
);

CREATE TABLE "Accounts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Value" numeric(10,2),
    "Status" integer NOT NULL,
    "EhParcelado" boolean,
    "QuantidadeParcelas" integer,
    "ParcelaAtual" integer,
    "CategoryId" integer NOT NULL,
    "DataAlteracao" timestamp without time zone NOT NULL DEFAULT (now()),
    "DataOperacao" text,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_Accounts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Accounts_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Accounts_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ItemLista" (
    "Id" serial NOT NULL,
    "ListaId" integer NOT NULL,
    "Descricao" character varying(200) NOT NULL,
    "Quantidade" integer,
    "Observacao" text,
    "Status" text,
    "Valor" numeric(10,2),
    "DataTarefa" date,
    "HorarioTarefa" time without time zone,
    "DataAlteracao" timestamp without time zone NOT NULL DEFAULT (now()),
    "UserId" integer NOT NULL,
    CONSTRAINT itemlista_pkey PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ItemLista_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT itemlista_listaid_fkey FOREIGN KEY ("ListaId") REFERENCES "Lista" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Banco" (
    "Id" serial NOT NULL,
    "NomeBanco" text NOT NULL,
    "Agencia" text,
    "NumeroConta" text,
    "TipoCartaoId" integer,
    "SaldoInicial" numeric(12,2) DEFAULT 0.0,
    "Ativo" boolean DEFAULT TRUE,
    "DataAlteracao" timestamp without time zone NOT NULL DEFAULT (now()),
    "UserId" integer,
    CONSTRAINT banco_pkey PRIMARY KEY ("Id"),
    CONSTRAINT banco_saldoinicial_check CHECK ("SaldoInicial" >= 0),
    CONSTRAINT "FK_Banco_AspNetUsers_UerId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT fk_banco_tipocartao FOREIGN KEY ("TipoCartaoId") REFERENCES "TipoCartao" ("Id")
);

CREATE TABLE "PessoaMovimentacao" (
    "Id" integer GENERATED ALWAYS AS IDENTITY,
    "NomePessoa" text,
    "CategoriaId" integer,
    "TipoMovimentacaoId" integer,
    "DataAlteracao" timestamp without time zone NOT NULL DEFAULT (now()),
    "UserId" integer,
    CONSTRAINT "PessoaMovimentacao_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT constraint_1 FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id"),
    CONSTRAINT constraint_2 FOREIGN KEY ("TipoMovimentacaoId") REFERENCES "TipoMovimentacao" ("Id")
);

CREATE TABLE "ContaVencimento" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ContaId" integer NOT NULL,
    "Dia" integer NOT NULL,
    "DataAlteracao" timestamp without time zone NOT NULL DEFAULT (now()),
    "UserId" integer,
    CONSTRAINT "ContaVencimento_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "ContaVencimento_ContaId_fkey" FOREIGN KEY ("ContaId") REFERENCES "Accounts" ("Id"),
    CONSTRAINT contavencimento_user_fkey FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id")
);

CREATE TABLE "Transactions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Date" timestamp with time zone NOT NULL,
    "Name" text NOT NULL,
    "Value" numeric(10,2),
    "IdAccount" integer,
    "CategoryId" integer,
    "Status" text NOT NULL,
    "EhParcelado" boolean NOT NULL DEFAULT FALSE,
    "ParcelaAtual" integer,
    "QuantidadeParcelas" integer,
    "Observacao" text,
    "DataAlteracao" timestamp without time zone NOT NULL DEFAULT (now()),
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_Transactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Transactions_Accounts_IdAccount" FOREIGN KEY ("IdAccount") REFERENCES "Accounts" ("Id"),
    CONSTRAINT "FK_Transactions_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ExtratoBancario" (
    "Id" serial NOT NULL,
    "DataImportacao" timestamp without time zone NOT NULL DEFAULT (now()),
    "DataInicioPeriodo" date,
    "DataFimPeriodo" date,
    "BancoId" integer,
    "TipoCartaoId" integer,
    "QuantidadeLancamentos" integer NOT NULL DEFAULT 0,
    "ValorTotal" numeric(10,2) NOT NULL DEFAULT 0.0,
    "LoteImportacaoId" uuid,
    "NomeArquivoOrigem" text,
    "Situacao" character varying(30) NOT NULL DEFAULT 'Concluido',
    "NomeArquivo" text,
    "UserId" integer NOT NULL,
    CONSTRAINT "ExtratoBancario_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT extratobancario_bancoid_fkey FOREIGN KEY ("BancoId") REFERENCES "Banco" ("Id") ON DELETE SET NULL,
    CONSTRAINT extratobancario_user_fkey FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "MovimentacaoDiaria" (
    "Id" serial NOT NULL,
    "DataMovimentacao" date NOT NULL,
    "BancoId" integer,
    "TipoCartaoId" integer,
    "TipoMovimentacaoId" integer,
    "Valor" numeric(10,2) NOT NULL,
    "TipoLancamento" text,
    "Descricao" text,
    "NomePessoaTransacao" text,
    "Identificador" text,
    "UserId" integer NOT NULL,
    CONSTRAINT movimentacaodiaria_pkey PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MovimentacaoDiaria_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT movimentacaodiaria_bancoid_fkey FOREIGN KEY ("BancoId") REFERENCES "Banco" ("Id") ON DELETE CASCADE,
    CONSTRAINT movimentacaodiaria_tipocartaoid_fkey FOREIGN KEY ("TipoCartaoId") REFERENCES "TipoCartao" ("Id") ON DELETE SET NULL,
    CONSTRAINT movimentacaodiaria_tipomovimentacaoid_fkey FOREIGN KEY ("TipoMovimentacaoId") REFERENCES "TipoMovimentacao" ("Id") ON DELETE SET NULL
);

CREATE TABLE "ExtratoBancarioItem" (
    "Id" serial NOT NULL,
    "ExtratoBancarioId" integer,
    "DataMovimentacao" date NOT NULL,
    "Valor" numeric(10,2) NOT NULL,
    "TipoLancamento" text NOT NULL,
    "Descricao" text,
    "Observacao" text,
    "PessoaMovimentacaoId" integer,
    "NomePessoaTransacao" text,
    "Identificador" text,
    "EhParcelado" boolean DEFAULT FALSE,
    "ParcelaAtual" integer,
    "QuantidadeParcelas" integer,
    "BancoId" integer,
    "TipoCartaoId" integer,
    "CategoriaId" integer,
    "NumeroFatura" character varying(20),
    "TipoMovimentacaoId" integer,
    "ChaveDescricao" character varying(200),
    "DataAlteracao" timestamp without time zone NOT NULL DEFAULT (now()),
    "GrupoParcelamento" character varying(60),
    "UserId" integer,
    CONSTRAINT "ExtratoBancarioItem_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ExtratoBancarioItem_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL,
    CONSTRAINT "extratoBancarioItem_bancoId_fkey" FOREIGN KEY ("CategoriaId") REFERENCES "Categories" ("Id"),
    CONSTRAINT extratobancarioitem_bancoid_fkey FOREIGN KEY ("BancoId") REFERENCES "Banco" ("Id") ON DELETE SET NULL,
    CONSTRAINT extratobancarioitem_extrato_fkey FOREIGN KEY ("ExtratoBancarioId") REFERENCES "ExtratoBancario" ("Id") ON DELETE CASCADE,
    CONSTRAINT extratobancarioitem_pessoamovimentacaoid_fkey FOREIGN KEY ("PessoaMovimentacaoId") REFERENCES "PessoaMovimentacao" ("Id"),
    CONSTRAINT extratobancarioitem_tipocartaoid_fkey FOREIGN KEY ("TipoCartaoId") REFERENCES "TipoCartao" ("Id") ON DELETE SET NULL,
    CONSTRAINT extratobancarioitem_tipomovimentacaoid_fkey FOREIGN KEY ("TipoMovimentacaoId") REFERENCES "TipoMovimentacao" ("Id") ON DELETE SET NULL
);

CREATE INDEX "IX_Accounts_CategoryId" ON "Accounts" ("CategoryId");

CREATE INDEX "IX_Accounts_UserId" ON "Accounts" ("UserId");

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_Categories_UserId" ON "Categories" ("UserId");

CREATE INDEX idx_extratobancarioitem_datamov ON "ExtratoBancarioItem" ("DataMovimentacao");

CREATE INDEX idx_extratobancarioitem_extrato ON "ExtratoBancarioItem" ("ExtratoBancarioId");

CREATE INDEX "IX_Transactions_IdAccount" ON "Transactions" ("IdAccount");

CREATE INDEX "IX_Transactions_UserId" ON "Transactions" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20261005163305_Baseline', '8.0.8');

COMMIT;

