-- DDL esperado pelo modelo EF (ContextDB + entidades), gerado em 03/10/2026 com:
--   dotnet ef dbcontext script -p MyFinanceAPI.Data -s MyFinanceAPI.Api
-- Gerado offline: não reflete o banco, e sim o que o código espera.
CREATE TABLE "AspNetRoles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);


CREATE TABLE "AspNetUsers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NomeUsuario" text NOT NULL,
    "StatusAtivo" boolean NOT NULL,
    "Role" text NOT NULL,
    "CriadoEm" timestamp with time zone NOT NULL,
    "AtualizadoEm" timestamp with time zone NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);


CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" integer NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserRoles" (
    "UserId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserTokens" (
    "UserId" integer NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "SubCategory" text NOT NULL,
    "NaturezaOperacao" integer NOT NULL,
    "Status" integer NOT NULL,
    "DataAlteracao" timestamp with time zone NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Categories_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "ExtratoBancario" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DataImportacao" timestamp with time zone NOT NULL,
    "DataInicioPeriodo" date,
    "DataFimPeriodo" date,
    "BancoId" integer NOT NULL,
    "TipoCartaoId" integer,
    "QuantidadeLancamentos" integer NOT NULL,
    "ValorTotal" numeric NOT NULL,
    "LoteImportacaoId" uuid NOT NULL,
    "NomeArquivoOrigem" character varying(255),
    "Situacao" character varying(50) NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_ExtratoBancario" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ExtratoBancario_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Lista" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" text NOT NULL,
    "TipoMovimentacao" integer NOT NULL,
    "Status" boolean NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_Lista" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Lista_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "TipoCartao" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NomeTipoCartao" text NOT NULL,
    "Descricao" text,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_TipoCartao" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TipoCartao_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "TipoMovimentacao" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NomeTipoMovimentacao" text NOT NULL,
    "Descricao" text NOT NULL,
    "ValorMeta" numeric NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_TipoMovimentacao" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TipoMovimentacao_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Accounts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Value" numeric NOT NULL,
    "Status" integer NOT NULL,
    "EhParcelado" boolean NOT NULL,
    "QuantidadeParcelas" integer,
    "ParcelaAtual" integer,
    "CategoryId" integer NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_Accounts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Accounts_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Accounts_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE
);


CREATE TABLE "ItemLista" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ListaId" integer NOT NULL,
    "Descricao" text NOT NULL,
    "Quantidade" integer,
    "Observacao" text,
    "Status" text,
    "Valor" numeric,
    "DataTarefa" date,
    "HorarioTarefa" time without time zone,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_ItemLista" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ItemLista_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ItemLista_Lista_ListaId" FOREIGN KEY ("ListaId") REFERENCES "Lista" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Banco" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NomeBanco" text NOT NULL,
    "Agencia" text,
    "NumeroConta" text,
    "TipoCartaoId" integer NOT NULL,
    "SaldoInicial" numeric NOT NULL,
    "Ativo" boolean,
    "DataAlteracao" timestamp with time zone NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_Banco" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Banco_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Banco_TipoCartao_TipoCartaoId" FOREIGN KEY ("TipoCartaoId") REFERENCES "TipoCartao" ("Id") ON DELETE CASCADE
);


CREATE TABLE "PessoaMovimentacao" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NomePessoa" text NOT NULL,
    "CategoriaId" integer,
    "TipoMovimentacaoId" integer,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_PessoaMovimentacao" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PessoaMovimentacao_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PessoaMovimentacao_Categories_CategoriaId" FOREIGN KEY ("CategoriaId") REFERENCES "Categories" ("Id"),
    CONSTRAINT "FK_PessoaMovimentacao_TipoMovimentacao_TipoMovimentacaoId" FOREIGN KEY ("TipoMovimentacaoId") REFERENCES "TipoMovimentacao" ("Id")
);


CREATE TABLE "VinculoTipoMovimentacao" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "ChaveDescricao" text NOT NULL,
    "DescricaoOriginalExemplo" text,
    "TipoMovimentacaoId" integer,
    "CategoriaId" integer,
    "Ativo" boolean NOT NULL,
    "DataCriacao" timestamp with time zone NOT NULL,
    "DataUltimoUso" timestamp with time zone,
    CONSTRAINT "PK_VinculoTipoMovimentacao" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_VinculoTipoMovimentacao_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_VinculoTipoMovimentacao_Categories_CategoriaId" FOREIGN KEY ("CategoriaId") REFERENCES "Categories" ("Id"),
    CONSTRAINT "FK_VinculoTipoMovimentacao_TipoMovimentacao_TipoMovimentacaoId" FOREIGN KEY ("TipoMovimentacaoId") REFERENCES "TipoMovimentacao" ("Id") ON DELETE SET NULL
);


CREATE TABLE "ContaVencimento" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ContaId" integer NOT NULL,
    "Dia" integer NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_ContaVencimento" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ContaVencimento_Accounts_ContaId" FOREIGN KEY ("ContaId") REFERENCES "Accounts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ContaVencimento_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Transactions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Date" timestamp with time zone NOT NULL,
    "Name" text NOT NULL,
    "Value" numeric,
    "IdAccount" integer,
    "CategoryId" integer,
    "Status" text NOT NULL,
    "EhParcelado" boolean NOT NULL,
    "ParcelaAtual" integer,
    "QuantidadeParcelas" integer,
    "Observacao" text,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_Transactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Transactions_Accounts_IdAccount" FOREIGN KEY ("IdAccount") REFERENCES "Accounts" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Transactions_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Transactions_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id")
);


CREATE TABLE "MovimentacaoDiaria" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DataMovimentacao" date NOT NULL,
    "BancoId" integer,
    "TipoCartaoId" integer,
    "TipoMovimentacaoId" integer,
    "Valor" numeric NOT NULL,
    "TipoLancamento" text NOT NULL,
    "Descricao" text,
    "NomePessoaTransacao" text,
    "Identificador" text,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_MovimentacaoDiaria" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MovimentacaoDiaria_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MovimentacaoDiaria_Banco_BancoId" FOREIGN KEY ("BancoId") REFERENCES "Banco" ("Id"),
    CONSTRAINT "FK_MovimentacaoDiaria_TipoCartao_TipoCartaoId" FOREIGN KEY ("TipoCartaoId") REFERENCES "TipoCartao" ("Id"),
    CONSTRAINT "FK_MovimentacaoDiaria_TipoMovimentacao_TipoMovimentacaoId" FOREIGN KEY ("TipoMovimentacaoId") REFERENCES "TipoMovimentacao" ("Id")
);


CREATE TABLE "ExtratoBancarioItem" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ExtratoBancarioId" integer,
    "DataMovimentacao" date NOT NULL,
    "Valor" numeric NOT NULL,
    "TipoLancamento" character varying(20) NOT NULL,
    "Descricao" character varying(500),
    "Observacao" text,
    "PessoaMovimentacaoId" integer,
    "NomePessoaTransacao" character varying(200),
    "Identificador" character varying(200),
    "EhParcelado" boolean,
    "ParcelaAtual" integer,
    "QuantidadeParcelas" integer,
    "BancoId" integer,
    "TipoCartaoId" integer,
    "CategoriaId" integer,
    "NumeroFatura" text,
    "TipoMovimentacaoId" integer,
    "ChaveDescricao" character varying(200),
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_ExtratoBancarioItem" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ExtratoBancarioItem_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ExtratoBancarioItem_Banco_BancoId" FOREIGN KEY ("BancoId") REFERENCES "Banco" ("Id"),
    CONSTRAINT "FK_ExtratoBancarioItem_Categories_CategoriaId" FOREIGN KEY ("CategoriaId") REFERENCES "Categories" ("Id"),
    CONSTRAINT "FK_ExtratoBancarioItem_ExtratoBancario_ExtratoBancarioId" FOREIGN KEY ("ExtratoBancarioId") REFERENCES "ExtratoBancario" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ExtratoBancarioItem_PessoaMovimentacao_PessoaMovimentacaoId" FOREIGN KEY ("PessoaMovimentacaoId") REFERENCES "PessoaMovimentacao" ("Id"),
    CONSTRAINT "FK_ExtratoBancarioItem_TipoCartao_TipoCartaoId" FOREIGN KEY ("TipoCartaoId") REFERENCES "TipoCartao" ("Id"),
    CONSTRAINT "FK_ExtratoBancarioItem_TipoMovimentacao_TipoMovimentacaoId" FOREIGN KEY ("TipoMovimentacaoId") REFERENCES "TipoMovimentacao" ("Id") ON DELETE SET NULL
);


CREATE INDEX "IX_Accounts_CategoryId" ON "Accounts" ("CategoryId");


CREATE INDEX "IX_Accounts_UserId" ON "Accounts" ("UserId");


CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");


CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");


CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");


CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");


CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");


CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");


CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");


CREATE INDEX "IX_Banco_TipoCartaoId" ON "Banco" ("TipoCartaoId");


CREATE INDEX "IX_Banco_UserId" ON "Banco" ("UserId");


CREATE INDEX "IX_Categories_UserId" ON "Categories" ("UserId");


CREATE INDEX "IX_ContaVencimento_ContaId" ON "ContaVencimento" ("ContaId");


CREATE INDEX "IX_ContaVencimento_UserId" ON "ContaVencimento" ("UserId");


CREATE INDEX "IX_ExtratoBancario_UserId" ON "ExtratoBancario" ("UserId");


CREATE INDEX "IX_ExtratoBancarioItem_BancoId" ON "ExtratoBancarioItem" ("BancoId");


CREATE INDEX "IX_ExtratoBancarioItem_CategoriaId" ON "ExtratoBancarioItem" ("CategoriaId");


CREATE INDEX "IX_ExtratoBancarioItem_ExtratoBancarioId" ON "ExtratoBancarioItem" ("ExtratoBancarioId");


CREATE INDEX "IX_ExtratoBancarioItem_PessoaMovimentacaoId" ON "ExtratoBancarioItem" ("PessoaMovimentacaoId");


CREATE INDEX "IX_ExtratoBancarioItem_TipoCartaoId" ON "ExtratoBancarioItem" ("TipoCartaoId");


CREATE INDEX "IX_ExtratoBancarioItem_TipoMovimentacaoId" ON "ExtratoBancarioItem" ("TipoMovimentacaoId");


CREATE INDEX "IX_ExtratoBancarioItem_UserId" ON "ExtratoBancarioItem" ("UserId");


CREATE INDEX "IX_ItemLista_ListaId" ON "ItemLista" ("ListaId");


CREATE INDEX "IX_ItemLista_UserId" ON "ItemLista" ("UserId");


CREATE INDEX "IX_Lista_UserId" ON "Lista" ("UserId");


CREATE INDEX "IX_MovimentacaoDiaria_BancoId" ON "MovimentacaoDiaria" ("BancoId");


CREATE INDEX "IX_MovimentacaoDiaria_TipoCartaoId" ON "MovimentacaoDiaria" ("TipoCartaoId");


CREATE INDEX "IX_MovimentacaoDiaria_TipoMovimentacaoId" ON "MovimentacaoDiaria" ("TipoMovimentacaoId");


CREATE INDEX "IX_MovimentacaoDiaria_UserId" ON "MovimentacaoDiaria" ("UserId");


CREATE INDEX "IX_PessoaMovimentacao_CategoriaId" ON "PessoaMovimentacao" ("CategoriaId");


CREATE INDEX "IX_PessoaMovimentacao_TipoMovimentacaoId" ON "PessoaMovimentacao" ("TipoMovimentacaoId");


CREATE INDEX "IX_PessoaMovimentacao_UserId" ON "PessoaMovimentacao" ("UserId");


CREATE INDEX "IX_TipoCartao_UserId" ON "TipoCartao" ("UserId");


CREATE INDEX "IX_TipoMovimentacao_UserId" ON "TipoMovimentacao" ("UserId");


CREATE INDEX "IX_Transactions_CategoryId" ON "Transactions" ("CategoryId");


CREATE INDEX "IX_Transactions_IdAccount" ON "Transactions" ("IdAccount");


CREATE INDEX "IX_Transactions_UserId" ON "Transactions" ("UserId");


CREATE INDEX "IX_VinculoTipoMovimentacao_CategoriaId" ON "VinculoTipoMovimentacao" ("CategoriaId");


CREATE INDEX "IX_VinculoTipoMovimentacao_TipoMovimentacaoId" ON "VinculoTipoMovimentacao" ("TipoMovimentacaoId");


CREATE INDEX "IX_VinculoTipoMovimentacao_UserId" ON "VinculoTipoMovimentacao" ("UserId");


