-- Export de schema do console do Neon (produção), copiado em 03/10/2026.
-- Fonte: painel do Neon. Não editar — é o registro de "antes do baseline".
CREATE SCHEMA "public";
CREATE TABLE "__EFMigrationsHistory" (
	"MigrationId" varchar(150),
	"ProductVersion" varchar(32) NOT NULL,
	CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY("MigrationId")
);
CREATE TABLE "Accounts" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "Accounts_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"Name" text NOT NULL,
	"Value" numeric(10, 2),
	"CategoryId" integer NOT NULL,
	"UserId" integer NOT NULL,
	"DataOperacao" text,
	"Status" integer NOT NULL,
	"EhParcelado" boolean,
	"ParcelaAtual" integer,
	"QuantidadeParcelas" integer,
	"DataAlteracao" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "PK_Accounts" PRIMARY KEY("Id")
);
CREATE TABLE "AspNetRoleClaims" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "AspNetRoleClaims_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"RoleId" integer NOT NULL,
	"ClaimType" text,
	"ClaimValue" text,
	CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY("Id")
);
CREATE TABLE "AspNetRoles" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "AspNetRoles_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"Name" varchar(256),
	"NormalizedName" varchar(256),
	"ConcurrencyStamp" text,
	CONSTRAINT "PK_AspNetRoles" PRIMARY KEY("Id")
);
CREATE TABLE "AspNetUserClaims" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "AspNetUserClaims_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"UserId" integer NOT NULL,
	"ClaimType" text,
	"ClaimValue" text,
	CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY("Id")
);
CREATE TABLE "AspNetUserLogins" (
	"LoginProvider" text,
	"ProviderKey" text,
	"ProviderDisplayName" text,
	"UserId" integer NOT NULL,
	CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY("LoginProvider","ProviderKey")
);
CREATE TABLE "AspNetUserRoles" (
	"UserId" integer,
	"RoleId" integer,
	CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY("UserId","RoleId")
);
CREATE TABLE "AspNetUsers" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "AspNetUsers_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"NomeUsuario" text NOT NULL,
	"StatusAtivo" boolean NOT NULL,
	"Role" text NOT NULL,
	"CriadoEm" timestamp with time zone NOT NULL,
	"AtualizadoEm" timestamp with time zone NOT NULL,
	"UserName" varchar(256),
	"NormalizedUserName" varchar(256),
	"Email" varchar(256),
	"NormalizedEmail" varchar(256),
	"EmailConfirmed" boolean NOT NULL,
	"PasswordHash" text,
	"SecurityStamp" text,
	"ConcurrencyStamp" text,
	"PhoneNumber" text,
	"PhoneNumberConfirmed" boolean NOT NULL,
	"TwoFactorEnabled" boolean NOT NULL,
	"LockoutEnd" timestamp with time zone,
	"LockoutEnabled" boolean NOT NULL,
	"AccessFailedCount" integer NOT NULL,
	CONSTRAINT "PK_AspNetUsers" PRIMARY KEY("Id")
);
CREATE TABLE "AspNetUserTokens" (
	"UserId" integer,
	"LoginProvider" text,
	"Name" text,
	"Value" text,
	CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY("UserId","LoginProvider","Name")
);
CREATE TABLE "Banco" (
	"Id" serial,
	"NomeBanco" text NOT NULL,
	"Agencia" text,
	"NumeroConta" text,
	"SaldoInicial" numeric(12, 2) DEFAULT '0',
	"Ativo" boolean DEFAULT true,
	"UserId" integer,
	"TipoCartaoId" integer,
	"DataAlteracao" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "banco_pkey" PRIMARY KEY("Id"),
	CONSTRAINT "banco_saldoinicial_check" CHECK (("SaldoInicial" >= (0)::numeric))
);
CREATE TABLE "Categories" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "Categories_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"Name" text NOT NULL,
	"SubCategory" text NOT NULL,
	"UserId" integer NOT NULL,
	"Status" integer NOT NULL,
	"NaturezaOperacao" integer,
	"DataAlteracao" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "PK_Categories" PRIMARY KEY("Id")
);
CREATE TABLE "ContaVencimento" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ContaVencimento_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ContaId" integer NOT NULL,
	"Dia" integer NOT NULL,
	"UserId" integer,
	"DataAlteracao" timestamp DEFAULT now() NOT NULL
);
CREATE TABLE "ExtratoBancario" (
	"Id" serial PRIMARY KEY,
	"UserId" integer NOT NULL,
	"NomeArquivo" text,
	"DataImportacao" timestamp DEFAULT now() NOT NULL,
	"DataInicioPeriodo" date,
	"DataFimPeriodo" date,
	"ValorTotal" numeric(10, 2) DEFAULT '0' NOT NULL,
	"BancoId" integer,
	"TipoCartaoId" integer,
	"LoteImportacaoId" uuid,
	"NomeArquivoOrigem" text,
	"Situacao" varchar(30) DEFAULT 'Concluido' NOT NULL,
	"QuantidadeLancamentos" integer DEFAULT 0 NOT NULL
);
CREATE TABLE "ExtratoBancarioItem" (
	"Id" serial PRIMARY KEY,
	"ExtratoBancarioId" integer,
	"DataMovimentacao" date NOT NULL,
	"Valor" numeric(10, 2) NOT NULL,
	"TipoLancamento" text NOT NULL,
	"Descricao" text,
	"NomePessoaTransacao" text,
	"Identificador" text,
	"BancoId" integer,
	"TipoCartaoId" integer,
	"TipoMovimentacaoId" integer,
	"UserId" integer,
	"ChaveDescricao" varchar(200),
	"CategoriaId" integer,
	"Observacao" text,
	"EhParcelado" boolean DEFAULT false,
	"ParcelaAtual" integer,
	"QuantidadeParcelas" integer,
	"GrupoParcelamento" varchar(60),
	"NumeroFatura" varchar(20),
	"PessoaMovimentacaoId" integer,
	"DataAlteracao" timestamp DEFAULT now() NOT NULL
);
CREATE TABLE "ItemLista" (
	"Id" serial,
	"ListaId" integer NOT NULL,
	"Descricao" varchar(200) NOT NULL,
	"Quantidade" integer,
	"UserId" integer NOT NULL,
	"Status" text,
	"Valor" numeric(10, 2),
	"DataTarefa" date,
	"HorarioTarefa" time,
	"Observacao" text,
	"DataAlteracao" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "itemlista_pkey" PRIMARY KEY("Id")
);
CREATE TABLE "Lista" (
	"Id" serial,
	"Nome" text NOT NULL,
	"TipoMovimentacao" integer,
	"Status" boolean,
	"UserId" integer NOT NULL,
	"DataAlteracao" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "lista_pkey" PRIMARY KEY("Id")
);
CREATE TABLE "MovimentacaoDiaria" (
	"Id" serial,
	"DataMovimentacao" date NOT NULL,
	"BancoId" integer,
	"TipoCartaoId" integer,
	"TipoMovimentacaoId" integer,
	"Valor" numeric(10, 2) NOT NULL,
	"UserId" integer NOT NULL,
	"Descricao" text,
	"TipoLancamento" text,
	"NomePessoaTransacao" text,
	"Identificador" text,
	CONSTRAINT "movimentacaodiaria_pkey" PRIMARY KEY("Id")
);
CREATE TABLE "PessoaMovimentacao" (
	"Id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "PessoaMovimentacao_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"CategoriaId" integer,
	"TipoMovimentacaoId" integer,
	"NomePessoa" text,
	"UserId" integer,
	"DataAlteracao" timestamp DEFAULT now() NOT NULL
);
CREATE TABLE "TipoCartao" (
	"Id" serial,
	"NomeTipoCartao" text NOT NULL,
	"Descricao" text,
	"UserId" integer,
	CONSTRAINT "tipocartao_pkey" PRIMARY KEY("Id")
);
CREATE TABLE "TipoMovimentacao" (
	"Id" serial,
	"NomeTipoMovimentacao" text NOT NULL,
	"Descricao" text,
	"ValorMeta" numeric(10, 2) DEFAULT '0',
	"UserId" integer,
	"DataAlteracao" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "tipomovimentacao_pkey" PRIMARY KEY("Id"),
	CONSTRAINT "tipomovimentacao_valormeta_check" CHECK (("ValorMeta" >= (0)::numeric))
);
CREATE TABLE "Transactions" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "Transactions_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"Date" timestamp with time zone NOT NULL,
	"Name" text NOT NULL,
	"Value" numeric(10, 2),
	"IdAccount" integer,
	"Status" text NOT NULL,
	"UserId" integer NOT NULL,
	"CategoryId" integer,
	"EhParcelado" boolean DEFAULT false NOT NULL,
	"ParcelaAtual" integer,
	"QuantidadeParcelas" integer,
	"Observacao" text,
	"DataAlteracao" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "PK_Transactions" PRIMARY KEY("Id")
);
CREATE UNIQUE INDEX "PK___EFMigrationsHistory" ON "__EFMigrationsHistory" ("MigrationId");
CREATE INDEX "IX_Accounts_CategoryId" ON "Accounts" ("CategoryId");
CREATE INDEX "IX_Accounts_UserId" ON "Accounts" ("UserId");
CREATE UNIQUE INDEX "PK_Accounts" ON "Accounts" ("Id");
CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
CREATE UNIQUE INDEX "PK_AspNetRoleClaims" ON "AspNetRoleClaims" ("Id");
CREATE UNIQUE INDEX "PK_AspNetRoles" ON "AspNetRoles" ("Id");
CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
CREATE UNIQUE INDEX "PK_AspNetUserClaims" ON "AspNetUserClaims" ("Id");
CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
CREATE UNIQUE INDEX "PK_AspNetUserLogins" ON "AspNetUserLogins" ("LoginProvider","ProviderKey");
CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
CREATE UNIQUE INDEX "PK_AspNetUserRoles" ON "AspNetUserRoles" ("UserId","RoleId");
CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
CREATE UNIQUE INDEX "PK_AspNetUsers" ON "AspNetUsers" ("Id");
CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
CREATE UNIQUE INDEX "PK_AspNetUserTokens" ON "AspNetUserTokens" ("UserId","LoginProvider","Name");
CREATE UNIQUE INDEX "banco_pkey" ON "Banco" ("Id");
CREATE INDEX "IX_Categories_UserId" ON "Categories" ("UserId");
CREATE UNIQUE INDEX "PK_Categories" ON "Categories" ("Id");
CREATE UNIQUE INDEX "ContaVencimento_pkey" ON "ContaVencimento" ("Id");
CREATE UNIQUE INDEX "ExtratoBancario_pkey" ON "ExtratoBancario" ("Id");
CREATE UNIQUE INDEX "ExtratoBancarioItem_pkey" ON "ExtratoBancarioItem" ("Id");
CREATE INDEX "idx_extratobancarioitem_datamov" ON "ExtratoBancarioItem" ("DataMovimentacao");
CREATE INDEX "idx_extratobancarioitem_extrato" ON "ExtratoBancarioItem" ("ExtratoBancarioId");
CREATE UNIQUE INDEX "itemlista_pkey" ON "ItemLista" ("Id");
CREATE UNIQUE INDEX "lista_pkey" ON "Lista" ("Id");
CREATE UNIQUE INDEX "movimentacaodiaria_pkey" ON "MovimentacaoDiaria" ("Id");
CREATE UNIQUE INDEX "PessoaMovimentacao_pkey" ON "PessoaMovimentacao" ("Id");
CREATE UNIQUE INDEX "tipocartao_pkey" ON "TipoCartao" ("Id");
CREATE UNIQUE INDEX "tipomovimentacao_pkey" ON "TipoMovimentacao" ("Id");
CREATE INDEX "IX_Transactions_IdAccount" ON "Transactions" ("IdAccount");
CREATE INDEX "IX_Transactions_UserId" ON "Transactions" ("UserId");
CREATE UNIQUE INDEX "PK_Transactions" ON "Transactions" ("Id");
ALTER TABLE "Accounts" ADD CONSTRAINT "FK_Accounts_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;
ALTER TABLE "Accounts" ADD CONSTRAINT "FK_Accounts_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories"("Id") ON DELETE CASCADE;
ALTER TABLE "AspNetRoleClaims" ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles"("Id") ON DELETE CASCADE;
ALTER TABLE "AspNetUserClaims" ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;
ALTER TABLE "AspNetUserLogins" ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;
ALTER TABLE "AspNetUserRoles" ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles"("Id") ON DELETE CASCADE;
ALTER TABLE "AspNetUserRoles" ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;
ALTER TABLE "AspNetUserTokens" ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;
ALTER TABLE "Banco" ADD CONSTRAINT "FK_Banco_AspNetUsers_UerId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;
ALTER TABLE "Banco" ADD CONSTRAINT "fk_banco_tipocartao" FOREIGN KEY ("TipoCartaoId") REFERENCES "TipoCartao"("Id");
ALTER TABLE "Categories" ADD CONSTRAINT "FK_Categories_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;
ALTER TABLE "ContaVencimento" ADD CONSTRAINT "ContaVencimento_ContaId_fkey" FOREIGN KEY ("ContaId") REFERENCES "Accounts"("Id");
ALTER TABLE "ContaVencimento" ADD CONSTRAINT "contavencimento_user_fkey" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id");
ALTER TABLE "ExtratoBancario" ADD CONSTRAINT "extratobancario_bancoid_fkey" FOREIGN KEY ("BancoId") REFERENCES "Banco"("Id") ON DELETE SET NULL;
ALTER TABLE "ExtratoBancario" ADD CONSTRAINT "extratobancario_user_fkey" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;
ALTER TABLE "ExtratoBancarioItem" ADD CONSTRAINT "extratobancarioitem_bancoid_fkey" FOREIGN KEY ("BancoId") REFERENCES "Banco"("Id") ON DELETE SET NULL;
ALTER TABLE "ExtratoBancarioItem" ADD CONSTRAINT "extratoBancarioItem_bancoId_fkey" FOREIGN KEY ("CategoriaId") REFERENCES "Categories"("Id");
ALTER TABLE "ExtratoBancarioItem" ADD CONSTRAINT "extratobancarioitem_extrato_fkey" FOREIGN KEY ("ExtratoBancarioId") REFERENCES "ExtratoBancario"("Id") ON DELETE CASCADE;
ALTER TABLE "ExtratoBancarioItem" ADD CONSTRAINT "extratobancarioitem_pessoamovimentacaoid_fkey" FOREIGN KEY ("PessoaMovimentacaoId") REFERENCES "PessoaMovimentacao"("Id");
ALTER TABLE "ExtratoBancarioItem" ADD CONSTRAINT "extratobancarioitem_tipocartaoid_fkey" FOREIGN KEY ("TipoCartaoId") REFERENCES "TipoCartao"("Id") ON DELETE SET NULL;
ALTER TABLE "ExtratoBancarioItem" ADD CONSTRAINT "extratobancarioitem_tipomovimentacaoid_fkey" FOREIGN KEY ("TipoMovimentacaoId") REFERENCES "TipoMovimentacao"("Id") ON DELETE SET NULL;
ALTER TABLE "ExtratoBancarioItem" ADD CONSTRAINT "FK_ExtratoBancarioItem_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE SET NULL;
ALTER TABLE "ItemLista" ADD CONSTRAINT "FK_ItemLista_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE RESTRICT;
ALTER TABLE "ItemLista" ADD CONSTRAINT "itemlista_listaid_fkey" FOREIGN KEY ("ListaId") REFERENCES "Lista"("Id") ON DELETE CASCADE;
ALTER TABLE "Lista" ADD CONSTRAINT "FK_Lista_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE RESTRICT;
ALTER TABLE "MovimentacaoDiaria" ADD CONSTRAINT "FK_MovimentacaoDiaria_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;
ALTER TABLE "MovimentacaoDiaria" ADD CONSTRAINT "movimentacaodiaria_bancoid_fkey" FOREIGN KEY ("BancoId") REFERENCES "Banco"("Id") ON DELETE CASCADE;
ALTER TABLE "MovimentacaoDiaria" ADD CONSTRAINT "movimentacaodiaria_tipocartaoid_fkey" FOREIGN KEY ("TipoCartaoId") REFERENCES "TipoCartao"("Id") ON DELETE SET NULL;
ALTER TABLE "MovimentacaoDiaria" ADD CONSTRAINT "movimentacaodiaria_tipomovimentacaoid_fkey" FOREIGN KEY ("TipoMovimentacaoId") REFERENCES "TipoMovimentacao"("Id") ON DELETE SET NULL;
ALTER TABLE "PessoaMovimentacao" ADD CONSTRAINT "constraint_1" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id");
ALTER TABLE "PessoaMovimentacao" ADD CONSTRAINT "constraint_2" FOREIGN KEY ("TipoMovimentacaoId") REFERENCES "TipoMovimentacao"("Id");
ALTER TABLE "TipoCartao" ADD CONSTRAINT "fk_tipocartao_aspnetusers" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id");
ALTER TABLE "TipoMovimentacao" ADD CONSTRAINT "fk_tipomovimentacao_aspnetusers" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id");
ALTER TABLE "Transactions" ADD CONSTRAINT "FK_Transactions_Accounts_IdAccount" FOREIGN KEY ("IdAccount") REFERENCES "Accounts"("Id");
ALTER TABLE "Transactions" ADD CONSTRAINT "FK_Transactions_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;
